name: Update Dependency README
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/readme-dependency.yml@main
    with:
      repository: ${{ github.repository }}
      actor: ${{ github.actor }}
    secrets:
      envPAT: ${{ secrets.PAT }}